# Generated by Django 5.0.6 on 2024-05-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TUITGroupsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_code', models.CharField(max_length=15)),
                ('group_name_uz', models.CharField(max_length=255)),
                ('group_name_ru', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'TUIT groups',
                'db_table': 'tuit_groups',
            },
        ),
        migrations.CreateModel(
            name='TUITSystemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=2, unique=True)),
                ('system_name_uz', models.CharField(max_length=255, unique=True)),
                ('system_name_ru', models.CharField(max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'TUIT systems',
                'db_table': 'tuit_systems',
            },
        ),
        migrations.CreateModel(
            name='TUITTypesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_name_uz', models.CharField(max_length=10, unique=True)),
                ('type_name_ru', models.CharField(max_length=10, null=True, unique=True)),
                ('type_description_uz', models.CharField(max_length=255, null=True)),
                ('type_description_ru', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'TUIT types',
                'db_table': 'tuit_types',
            },
        ),
    ]
