# Generated by Django 5.0.6 on 2024-05-19 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_1', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitgroupsmodel',
            name='group_code',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='tuitsystemsmodel',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='tuittypesmodel',
            name='type_name_ru',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tuittypesmodel',
            name='type_name_uz',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='TUITContactsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'TUIT Contacts',
                'db_table': 'tuit_contacts',
            },
        ),
        migrations.CreateModel(
            name='TUITFaqModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_uz', models.CharField(max_length=100, unique=True)),
                ('question_ru', models.CharField(max_length=100, null=True, unique=True)),
                ('answer_uz', models.CharField(max_length=255, null=True)),
                ('answer_ru', models.CharField(max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'TUIT FAQ',
                'db_table': 'tuit_faq',
            },
        ),
        migrations.CreateModel(
            name='TUITRequirementsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('req_title_uz', models.CharField(max_length=100, unique=True)),
                ('req_title_ru', models.CharField(max_length=100, null=True, unique=True)),
                ('req_description_uz', models.CharField(max_length=255, null=True)),
                ('req_description_ru', models.CharField(max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'TUIT requirements',
                'db_table': 'tuit_requirements',
            },
        ),
    ]
