# Generated by Django 5.0.6 on 2024-05-22 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp_1', '0004_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TUITPublicationsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publication_code', models.CharField(max_length=150)),
                ('publication_name_uz', models.CharField(max_length=255)),
                ('publication_name_ru', models.CharField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'TUIT publications',
                'db_table': 'tuit_publications',
            },
        ),
        migrations.RenameModel(
            old_name='TUITTypesModel',
            new_name='TUITPapersModel',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.AlterModelOptions(
            name='tuitpapersmodel',
            options={'verbose_name_plural': 'TUIT papers'},
        ),
        migrations.RenameField(
            model_name='tuitcontactsmodel',
            old_name='last_name',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='tuitpapersmodel',
            old_name='type_description_ru',
            new_name='paper_description_ru',
        ),
        migrations.RenameField(
            model_name='tuitpapersmodel',
            old_name='type_description_uz',
            new_name='paper_description_uz',
        ),
        migrations.RenameField(
            model_name='tuitpapersmodel',
            old_name='type_name_ru',
            new_name='paper_name_ru',
        ),
        migrations.RenameField(
            model_name='tuitpapersmodel',
            old_name='type_name_uz',
            new_name='paper_name_uz',
        ),
        migrations.AlterModelTable(
            name='tuitpapersmodel',
            table='tuit_papers',
        ),
        migrations.RenameModel(
            old_name='TUITSystemsModel',
            new_name='TUITMainModel',
        ),
        migrations.AddField(
            model_name='tuitpublicationsmodel',
            name='publication_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp_1.tuitmainmodel'),
        ),
        migrations.DeleteModel(
            name='TUITGroupsModel',
        ),
    ]
